# Generated by Django 4.0.4 on 2022-04-30 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_image', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Completed', 'COMPLETED'), ('Releasing', 'RELEASING'), ('Cancelled', 'CANCELLED'), ('Planned', 'PLANNED')], max_length=15)),
                ('media_format', models.CharField(choices=[('Comic', 'COMIC'), ('Web Comic', 'WEB COMIC'), ('Manga', 'MANGA')], max_length=15)),
                ('comicvine_volume_id', models.PositiveIntegerField(blank=True, null=True)),
                ('locg_series_id', models.PositiveIntegerField(blank=True, null=True)),
                ('anilist_manga_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mal_manga_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tankobon_manga_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('characters', models.ManyToManyField(blank=True, to='common.character')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.creator')),
                ('genres', models.ManyToManyField(blank=True, to='common.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('absolute_number', models.PositiveIntegerField()),
                ('volume_number', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('comicvine_issue_id', models.PositiveIntegerField(blank=True, null=True)),
                ('locg_comic_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('comic_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comic')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.publisher'),
        ),
    ]
