# Generated by Django 4.1 on 2022-08-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_alter_comic_chapter_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='banner_image',
        ),
    ]
