# Generated by Django 4.1 on 2022-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_remove_comic_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
