# Generated by Django 4.1 on 2022-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='creator',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
