# Generated by Django 4.1 on 2022-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_character_slug_comic_slug_creator_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
