# Generated by Django 4.1 on 2022-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_alter_comic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
